version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/twitter-clone
    ports:
      - 8000:8000
    image: app:twitter-clone
    container_name: twitter_clone_django
    command: python manage.py runserver 0.0.0.0:8000
